#!/usr/bin/env python3
"""
VEHBench extraction pipeline.

Reads normalized MinerU documents and extracts a compact, benchmark-oriented
record using Ark GLM. Metadata is copied from normalized_docs and never
generated by the model.
"""

import argparse
import json
import os
import re
import sys
import time
from pathlib import Path

import yaml
from dotenv import load_dotenv
from openai import OpenAI


SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
LOCAL_ENV_PATH = PROJECT_ROOT / "pipelines" / "download" / ".env"
FALLBACK_ENV_PATH = PROJECT_ROOT.parent / "EH-LLM" / "pipelines" / "download" / ".env"

for env_path in (LOCAL_ENV_PATH, FALLBACK_ENV_PATH):
    if env_path.exists():
        load_dotenv(env_path, override=False)

ARK_API_KEY = os.getenv("ARK_API_KEY", "")

NORMALIZED_DIR = PROJECT_ROOT / "normalized_docs"
EXTRACTED_DIR = PROJECT_ROOT / "data_registry" / "extracted"
INVALID_DIR = PROJECT_ROOT / "data_registry" / "extracted_invalid"
SCHEMA_PATH = PROJECT_ROOT / "schemas" / "vehbench_extract_v1.yaml"

for directory in (EXTRACTED_DIR, INVALID_DIR):
    directory.mkdir(parents=True, exist_ok=True)

LLM_MODEL = "glm-4-7-251222"
LLM_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3"
MAX_CONTEXT_CHARS = 60000
EVIDENCE_KEYS = ("quote", "section", "source_type")
QUANT_KEYWORDS = (
    "power", "frequency", "acceleration", "resistance", "voltage", "current",
    "proof mass", "tip mass", "sliding mass", "load", "beam", "cantilever",
    "pvdf", "pzt", "piezo", "thickness", "length", "width", "bandwidth",
    "experiment", "prototype", "design", "results"
)
KEEP_HEADING_KEYWORDS = (
    "abstract", "design", "model", "method", "experiment", "result",
    "discussion", "conclusion", "validation", "analysis", "fabrication",
    "description"
)
DROP_HEADING_KEYWORDS = (
    "reference", "acknowledg", "author contribution", "funding",
    "conflict", "appendix"
)


def color(text: str, code: str) -> str:
    if sys.stdout.isatty():
        return f"\033[{code}m{text}\033[0m"
    return text


def create_client() -> OpenAI:
    if not ARK_API_KEY:
        print("ERROR: ARK_API_KEY not set.")
        sys.exit(1)
    return OpenAI(base_url=LLM_BASE_URL, api_key=ARK_API_KEY)


def load_schema(schema_path: Path) -> dict:
    suffix = schema_path.suffix.lower()
    with open(schema_path, "r", encoding="utf-8") as handle:
        if suffix == ".json":
            return json.load(handle)
        return yaml.safe_load(handle)


def build_system_prompt(schema: dict) -> str:
    yaml_schema = yaml.dump(schema, allow_unicode=True, sort_keys=False)
    return f"""You are extracting VEHBench records for vibration energy harvesters.

TARGET LLM OUTPUT SCHEMA (YAML):
{yaml_schema}

RULES:
1. Output JSON only. No markdown fences, no commentary.
2. Output exactly these top-level keys:
   configuration, proof_mass, geometry, excitation, load, output, evidence
3. Do not output metadata. The pipeline will attach paper_id, doi, title, year,
   and journal itself.
4. Do not output application domain, novelty, claim, limitation, mechanism, or
   any extra fields.
5. Extract only what is explicitly supported by the provided paper content.
   If a field is unclear, use null.
6. Convert units to the schema units.
7. Evidence must be field-level. The evidence object must mirror the extracted
   fields. For every non-null extracted leaf, provide an evidence leaf object
   with quote, section, and source_type.
8. quote must be a short verbatim excerpt copied from the paper content.
9. source_type must be one of: section, table, figure_caption, abstract, title,
   unknown.
10. Use cantilever whenever the harvester is a cantilever beam design.
11. proof_mass means explicit proof/tip/sliding/mobile mass. Use null if the
    paper does not make this clear.
"""


def should_include_section(heading: str, text: str) -> bool:
    heading_l = (heading or "").strip().lower()
    text_l = (text or "").strip().lower()

    if not text_l:
        return False
    if any(keyword in heading_l for keyword in DROP_HEADING_KEYWORDS):
        return False
    if any(keyword in heading_l for keyword in KEEP_HEADING_KEYWORDS):
        return True
    return any(keyword in text_l for keyword in QUANT_KEYWORDS)


def build_llm_context(doc: dict) -> str:
    content_parts = [
        "PAPER CONTEXT (metadata for reference only; do not output metadata):",
        f"paper_id: {doc.get('paper_id', '')}",
        f"doi: {doc.get('doi', '')}",
        f"title: {doc.get('title', '')}",
        f"year: {doc.get('year', '')}",
        f"journal: {doc.get('venue', '')}",
    ]

    for sec in doc.get("sections", []):
        heading = sec.get("heading", "")
        text = sec.get("text", "")
        if should_include_section(heading, text):
            content_parts.append(f"--- SECTION: {heading} ---\n{text}")

    for idx, tab in enumerate(doc.get("tables", []), 1):
        content = (tab.get("content") or "").strip()
        if content:
            content_parts.append(
                f"--- TABLE {idx} (Page {tab.get('page')}) ---\n{content}"
            )

    for idx, fig in enumerate(doc.get("figures", []), 1):
        caption = (fig.get("caption") or "").strip()
        if caption and any(keyword in caption.lower() for keyword in QUANT_KEYWORDS):
            content_parts.append(
                f"--- FIGURE CAPTION {idx} (Page {fig.get('page')}) ---\n{caption}"
            )

    full_text = "\n\n".join(content_parts)
    if len(full_text) > MAX_CONTEXT_CHARS:
        full_text = full_text[:MAX_CONTEXT_CHARS]
    return full_text


def extract_json_block(content: str) -> str:
    stripped = content.strip()
    if stripped.startswith("```"):
        match = re.search(r"```(?:json)?\s*(.*?)```", stripped, flags=re.DOTALL)
        if match:
            return match.group(1).strip()

    start = stripped.find("{")
    end = stripped.rfind("}")
    if start != -1 and end != -1 and end > start:
        return stripped[start:end + 1]
    return stripped


def request_extraction(client: OpenAI, sys_prompt: str, doc: dict) -> dict:
    user_prompt = (
        "Extract a VEHBench record from the following paper content.\n\n"
        f"{build_llm_context(doc)}"
    )
    last_content = ""

    for attempt in range(3):
        try:
            response = client.chat.completions.create(
                model=LLM_MODEL,
                messages=[
                    {"role": "system", "content": sys_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.1,
                max_tokens=4000,
            )
            last_content = response.choices[0].message.content.strip()
            return {
                "ok": True,
                "data": json.loads(extract_json_block(last_content)),
                "raw_output": last_content,
            }
        except json.JSONDecodeError as exc:
            if attempt < 2:
                time.sleep(2)
                continue
            return {
                "ok": False,
                "error": f"JSON decode error: {exc}",
                "raw_output": last_content,
            }
        except Exception as exc:
            if attempt < 2:
                time.sleep(5)
                continue
            return {
                "ok": False,
                "error": str(exc),
                "raw_output": last_content,
            }


def build_null_template(schema_node: dict):
    if schema_node.get("type") == "object":
        return {
            name: build_null_template(child)
            for name, child in schema_node.get("properties", {}).items()
        }
    return None


def coerce_to_schema(value, schema_node: dict):
    if schema_node.get("type") == "object":
        src = value if isinstance(value, dict) else {}
        return {
            name: coerce_to_schema(src.get(name), child)
            for name, child in schema_node.get("properties", {}).items()
        }
    if value is None:
        return None
    return value


def copy_metadata(doc: dict, doc_path: Path) -> dict:
    return {
        "paper_id": doc.get("paper_id") or doc_path.stem,
        "doi": doc.get("doi") or None,
        "title": doc.get("title") or None,
        "year": doc.get("year"),
        "journal": doc.get("venue") or None,
    }


def build_record(doc: dict, doc_path: Path, llm_output: dict, schema: dict) -> dict:
    record = {"metadata": copy_metadata(doc, doc_path)}
    template = build_null_template(schema)
    template.update(coerce_to_schema(llm_output, schema))
    record.update(template)
    return record


def join_path(prefix: str, name: str) -> str:
    return f"{prefix}.{name}" if prefix else name


def validate_schema_value(value, schema_node: dict, path: str) -> list[str]:
    errors = []
    node_type = schema_node.get("type")

    if node_type == "object":
        if value is None:
            if schema_node.get("required"):
                errors.append(f"{path} missing")
            return errors
        if not isinstance(value, dict):
            errors.append(f"{path} must be an object")
            return errors
        for name, child in schema_node.get("properties", {}).items():
            errors.extend(
                validate_schema_value(value.get(name), child, join_path(path, name))
            )
        return errors

    if value is None:
        if schema_node.get("required") and not schema_node.get("nullable", False):
            errors.append(f"{path} missing")
        return errors

    if node_type == "string" and not isinstance(value, str):
        errors.append(f"{path} must be a string")
    elif node_type == "number" and (not isinstance(value, (int, float)) or isinstance(value, bool)):
        errors.append(f"{path} must be a number")
    elif node_type == "boolean" and not isinstance(value, bool):
        errors.append(f"{path} must be a boolean")

    allowed = schema_node.get("enum")
    if allowed and value not in allowed:
        errors.append(f"{path} must be one of {allowed}")
    return errors


def get_nested(obj: dict, path: tuple[str, ...]):
    current = obj
    for part in path:
        if not isinstance(current, dict):
            return None
        current = current.get(part)
    return current


def iter_leaf_paths(schema_node: dict, prefix: tuple[str, ...] = ()):
    if schema_node.get("type") == "object":
        for name, child in schema_node.get("properties", {}).items():
            yield from iter_leaf_paths(child, prefix + (name,))
    else:
        yield prefix


def validate_field_level_evidence(record: dict, schema: dict) -> list[str]:
    errors = []
    evidence = record.get("evidence", {})

    for top_key in ("configuration", "proof_mass", "geometry", "excitation", "load", "output"):
        top_schema = schema["properties"][top_key]
        for path in iter_leaf_paths(top_schema, (top_key,)):
            value = get_nested(record, path)
            evidence_leaf = get_nested(evidence, path)
            path_str = ".".join(path)

            if value is None:
                continue

            if not isinstance(evidence_leaf, dict):
                errors.append(f"evidence missing for {path_str}")
                continue

            quote = evidence_leaf.get("quote")
            source_type = evidence_leaf.get("source_type")
            section = evidence_leaf.get("section")

            if not quote:
                errors.append(f"evidence.quote missing for {path_str}")
            if not source_type:
                errors.append(f"evidence.source_type missing for {path_str}")
            if not section:
                errors.append(f"evidence.section missing for {path_str}")

    return errors


def validate_record(record: dict, schema: dict, doc: dict) -> tuple[list[str], list[str]]:
    errors = []
    warnings = []
    metadata = record.get("metadata", {})

    if not metadata.get("paper_id"):
        errors.append("metadata.paper_id missing")
    if not metadata.get("title"):
        errors.append("metadata.title missing")
    if metadata.get("year") is None:
        errors.append("metadata.year missing")

    source_doi = doc.get("doi")
    if source_doi and metadata.get("doi") != source_doi:
        errors.append("metadata.doi lost from normalized_doc")
    if not source_doi:
        warnings.append("normalized_doc has no doi")

    for key in schema.get("properties", {}):
        errors.extend(
            validate_schema_value(record.get(key), schema["properties"][key], key)
        )

    output = record.get("output", {})
    if all(
        output.get(field) is None
        for field in (
            "resonant_frequency_Hz",
            "output_power_W",
            "open_circuit_voltage_V",
            "short_circuit_current_A",
            "bandwidth_Hz",
        )
    ):
        errors.append("output has no populated metric")

    excitation = record.get("excitation", {})
    if (
        excitation.get("frequency_Hz") is None
        and excitation.get("acceleration_g") is None
        and excitation.get("displacement_mm") is None
    ):
        warnings.append("excitation has no numeric condition")

    geometry = record.get("geometry", {})
    if all(value is None for value in geometry.values()):
        warnings.append("geometry has no populated dimensions")

    errors.extend(validate_field_level_evidence(record, schema))
    return errors, warnings


def save_invalid_report(doc_path: Path, doc: dict, llm_result: dict,
                        record: dict | None, errors: list[str], warnings: list[str]):
    report = {
        "status": "invalid",
        "doc_path": str(doc_path),
        "doc_metadata": copy_metadata(doc, doc_path),
        "errors": errors,
        "warnings": warnings,
        "record": record,
        "llm_result": llm_result,
    }
    report_path = INVALID_DIR / doc_path.name
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2))


def collect_docs(limit: int | None, paper_id: str | None, overwrite: bool) -> list[Path]:
    docs_to_process = []
    for doc_path in sorted(NORMALIZED_DIR.glob("*.json")):
        if paper_id and paper_id not in doc_path.stem:
            continue
        out_path = EXTRACTED_DIR / doc_path.name
        if not overwrite and out_path.exists():
            continue
        docs_to_process.append(doc_path)
    if limit:
        docs_to_process = docs_to_process[:limit]
    return docs_to_process


def run(limit: int = None, paper_id: str = None,
        schema_path: Path = SCHEMA_PATH, overwrite: bool = False):
    if not schema_path.exists():
        print(f"ERROR: schema not found: {schema_path}")
        sys.exit(1)

    schema = load_schema(schema_path)
    sys_prompt = build_system_prompt(schema)
    client = create_client()

    docs_to_process = collect_docs(limit=limit, paper_id=paper_id, overwrite=overwrite)
    print(f"Starting extraction for {len(docs_to_process)} documents...", flush=True)

    success_count = 0
    invalid_count = 0
    error_count = 0

    for idx, doc_path in enumerate(docs_to_process, 1):
        print(f"[{idx}/{len(docs_to_process)}] Processing {doc_path.stem}...", flush=True)

        try:
            doc = json.loads(doc_path.read_text(encoding="utf-8", errors="replace"))
        except Exception as exc:
            print(color(f"  INVALID: failed to parse {doc_path.name}: {exc}", "31"), flush=True)
            error_count += 1
            continue

        started_at = time.time()
        llm_result = request_extraction(client, sys_prompt, doc)
        duration_s = time.time() - started_at
        out_path = EXTRACTED_DIR / doc_path.name
        invalid_path = INVALID_DIR / doc_path.name

        if not llm_result.get("ok"):
            print(color(f"  INVALID ({duration_s:.1f}s): {llm_result['error']}", "31"), flush=True)
            save_invalid_report(doc_path, doc, llm_result, None, [llm_result["error"]], [])
            if out_path.exists():
                out_path.unlink()
            error_count += 1
            continue

        record = build_record(doc, doc_path, llm_result["data"], schema)
        errors, warnings = validate_record(record, schema, doc)

        if errors:
            print(color(f"  INVALID ({duration_s:.1f}s): {'; '.join(errors[:3])}", "31"), flush=True)
            if warnings:
                print(color(f"  WARN: {'; '.join(warnings[:3])}", "33"), flush=True)
            save_invalid_report(doc_path, doc, llm_result, record, errors, warnings)
            if out_path.exists():
                out_path.unlink()
            invalid_count += 1
            continue

        out_path.write_text(json.dumps(record, ensure_ascii=False, indent=2))
        if invalid_path.exists():
            invalid_path.unlink()

        if warnings:
            print(color(f"  OK with warnings ({duration_s:.1f}s): {'; '.join(warnings[:3])}", "33"), flush=True)
        else:
            print(f"  OK ({duration_s:.1f}s)", flush=True)
        success_count += 1

    print("=" * 50, flush=True)
    print("Extraction complete", flush=True)
    print(f"  valid:   {success_count}", flush=True)
    print(f"  invalid: {invalid_count}", flush=True)
    print(f"  errors:  {error_count}", flush=True)
    print("=" * 50, flush=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--paper-id", type=str, default=None)
    parser.add_argument("--schema-path", type=Path, default=SCHEMA_PATH)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    run(
        limit=args.limit,
        paper_id=args.paper_id,
        schema_path=args.schema_path,
        overwrite=args.overwrite,
    )


if __name__ == "__main__":
    main()
